/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */
import java.io.File

rootProject.name = "KAIMUX-community"

// Automatically include subprojects if they contain a "target_paths" file
rootDir.listFiles()
    ?.filter { it.isDirectory && File(it, "target_paths").exists() }
    ?.forEach { include(it.name) }
